<a href="https://colab.research.google.com/github/tanyagupta1/Machine-Learning/blob/main/k_fold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits

In [6]:
digits=load_digits()
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [ ]:
log_reg_model=LogisticRegression()
log_reg_model.fit(X_train,Y_train)
log_reg_model.score(X_test,Y_test)

In [8]:
svm_model=SVC()
svm_model.fit(X_train,Y_train)
svm_model.score(X_test,Y_test)

0.987037037037037

In [9]:
forest_model=RandomForestClassifier()
forest_model.fit(X_train,Y_train)
forest_model.score(X_test,Y_test)

0.9833333333333333

In [10]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)

In [14]:
for a,b in kf.split([1,2,3,4,5,6,7,8,9]):
  print(a)
  print(b)
  print()

[3 4 5 6 7 8]
[0 1 2]

[0 1 2 6 7 8]
[3 4 5]

[0 1 2 3 4 5]
[6 7 8]



In [15]:
def get_score(model,X_train,X_test,Y_train,Y_test):
  model.fit(X_train,Y_train)
  return model.score(X_test,Y_test)

In [16]:
get_score(SVC(),X_train,X_test,Y_train,Y_test)

0.987037037037037

In [ ]:
scores_l=[]
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
  X_train,X_test,Y_train,Y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
  scores_l.append(get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test))
  scores_svm.append(get_score(SVC(),X_train,X_test,Y_train,Y_test))
  scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test))


In [20]:
scores_l
scores_svm
scores_rf

[0.9298831385642737, 0.9616026711185309, 0.9315525876460768]

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)