<a href="https://colab.research.google.com/github/tanyagupta1/Machine-Learning/blob/main/DL/pytorch/mat_mul.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [5]:
torch.manual_seed(7)
features=torch.randn((1,5))
weights=torch.randn_like(features)
weights=weights.view(5,1)
bias=torch.randn((1,1))

In [6]:
ans = torch.add(torch.matmul(features,weights),bias)
print(activation(ans))

tensor([[0.1595]])


In [8]:
torch.manual_seed(7)
features = torch.randn((1,3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1
W1 = torch.randn((n_input,n_hidden))
W2 = torch.randn((n_hidden,n_output))

B1 = torch.randn((1,n_hidden))
B2 = torch.randn(1,n_output)

int1 = activation(torch.matmul(features,W1)+B1)

ans=activation(torch.matmul(int1,W2)+B2)

ans

tensor([[0.3171]])

In [10]:
import numpy as np

a = np.random.rand(4,3)
print(a)
b=torch.from_numpy(a)
print(b)
c=b.numpy()
print(c)

[[0.63864817 0.0269188  0.53403834]
 [0.92696584 0.05535916 0.35162925]
 [0.66144361 0.04230353 0.15791612]
 [0.39871409 0.81884864 0.06801834]]
tensor([[0.6386, 0.0269, 0.5340],
        [0.9270, 0.0554, 0.3516],
        [0.6614, 0.0423, 0.1579],
        [0.3987, 0.8188, 0.0680]], dtype=torch.float64)
[[0.63864817 0.0269188  0.53403834]
 [0.92696584 0.05535916 0.35162925]
 [0.66144361 0.04230353 0.15791612]
 [0.39871409 0.81884864 0.06801834]]
