<a href="https://colab.research.google.com/github/tanyagupta1/Machine-Learning/blob/main/DL/pytorch_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [14]:
x=torch.zeros(2,2)
y=torch.rand(2)
z=torch.rand(1,2)
print(x)
print(y)
print(z)
a=torch.ones(2,2,dtype=torch.float16)
print(a.size(),a.dtype)
a=torch.tensor([1,2,3],dtype=torch.float32)
print(a)
b=torch.ones(3)
print(a+b)
c=torch.add(a,b)
print(c)
a.add_(b)
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([0.4831, 0.6635])
tensor([[0.0312, 0.0704]])
torch.Size([2, 2]) torch.float16
tensor([1., 2., 3.])
tensor([2., 3., 4.])
tensor([2., 3., 4.])
tensor([2., 3., 4.])


In [18]:
a=torch.rand(4,3)
print(a)
b=a[:,0]
print(b)
reshaped_a = a.view(12) #for reshaping
a_2=a.view(-1,6) #automatically determines size
print(reshaped_a)
print(a_2)

tensor([[0.2100, 0.0718, 0.4093],
        [0.4917, 0.6315, 0.7892],
        [0.3900, 0.4762, 0.4546],
        [0.3871, 0.7599, 0.9925]])
tensor([0.2100, 0.4917, 0.3900, 0.3871])
tensor([0.2100, 0.0718, 0.4093, 0.4917, 0.6315, 0.7892, 0.3900, 0.4762, 0.4546,
        0.3871, 0.7599, 0.9925])
tensor([[0.2100, 0.0718, 0.4093, 0.4917, 0.6315, 0.7892],
        [0.3900, 0.4762, 0.4546, 0.3871, 0.7599, 0.9925]])


In [20]:
#tensor to numpy
import numpy as np
a=torch.ones(5)
b=a.numpy()
print(type(b))
c=torch.from_numpy(b)
print(type(c))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
