<a href="https://colab.research.google.com/github/tanyagupta1/Machine-Learning/blob/main/DL/time_window.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [24]:
dataset=tf.data.Dataset.range(10)
# for val in dataset:
#   print(val.numpy())
dataset=dataset.window(5,shift=1,drop_remainder=True)

In [25]:
for win in dataset:
  # print(win.numpy())
  for i in win:
    print(i.numpy(),end=" ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [26]:
dataset=dataset.flat_map(lambda win: win.batch(5))
dataset=dataset.map(lambda win:(win[:-1],win[-1:]))
dataset = dataset.shuffle(buffer_size=10)
dataset = dataset.batch(2).prefetch(1)
for x,y in dataset:
  print(x.numpy(),y.numpy())

[[0 1 2 3]
 [2 3 4 5]] [[4]
 [6]]
[[5 6 7 8]
 [1 2 3 4]] [[9]
 [5]]
[[4 5 6 7]
 [3 4 5 6]] [[8]
 [7]]


In [27]:
def window_dataset(series,window_size,batch_size=32,shuffle_buffer=1000):
  dataset=tf.data.Dataset.from_tensor_slices(series)
  dataset=dataset.window(window_size+1,shift=1,drop_remainder=True)
  dataset=dataset.flat_map(lambda win:win.batch(window_size+1))
  dataset=dataset.shuffle(shuffle_buffer)
  dataset=dataset.map(lambda win:(win[:-1],win[-1:]))
  dataset=dataset.batch(batch_size).prefetch(1)
  return dataset